name: Publish Package to Azure Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build and publish package
        working-directory: my_python_project/my_package
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url "https://pkgs.dev.azure.com/khimaja111/ADOdemo/_packaging/PythonPackage/pypi/upload/" --password ${{ secrets.AZURE_DEVOPS_FEED_API_KEY }} --username HIMAJA dist/*
