name: Upload Package Version 2

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  # push:
  #   branches:
  #     - main  # Adjust branch name if necessary

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify Python version

      - name: Install twine
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install twine

      - name: Build and publish package
        working-directory: my_python_project/my_package
        run: |
          python setup.py sdist bdist_wheel
          twine upload -r PythonPackageTwine --config-file ../../.pypirc dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.AZURE_DEVOPS_FEED_API_KEY }}
